project_id = "fbsuhhmuwkqzpslonlxt"

[functions.accounts]
verify_jwt = false

[functions.cards]
verify_jwt = false

[functions.transactions]
verify_jwt = false

[functions.installments]
verify_jwt = false

[functions.invoices]
verify_jwt = false

[functions.pay-invoice]
verify_jwt = false

[functions.reports]
verify_jwt = false

[functions.chat-messages]
verify_jwt = false

[functions.personal-coach]
verify_jwt = false

[functions.secrets-gemini]
verify_jwt = false
